### ISSUE TITLE
Review FlowHandler location referral and ExternalRedirect semantics [SWF-588]

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-webflow#1403]
**[Keith Donald](https://jira.spring.io/secure/ViewProfile.jspa?name=kdonald)** opened **[SWF-588](https://jira.spring.io/browse/SWF-588?redirect=false)** and commented

Consider
- syntax for specifying context relative redirects
- servlet relative redirects (the default?)
- external url redirects
  Review with Juergen to ensure consistency with Spring MVC behavior.

---

**Affects:** 2.0.0.RC1

1 votes, 1 watchers

**Comment by yauheni-sidarenka** [comment]
Looks like this improvement removed the ability to use external redirect for links with custom (non-HTTP(S)) URI scheme. https://github.com/spring-projects/spring-webflow/commit/12423471b5a059a5713f6bcdbef7e67817309634
