### ISSUE TITLE
Spring Faces migration to Jakarta EE

### ISSUE THREAD

**Issue by Zorrodude** [spring-projects/spring-webflow#1793]
Does anyone know what the plan is for spring-faces and jakarta migration?
BR

**Comment by martin654** [comment]
This would be much appreciated. I see that @iptga made a PR. We are excited about it!

**Comment by Zorrodude** [comment]
Really good news, big credits to @iptga.

**Comment by Zorrodude** [comment]
Does anyone know what the time plan is for the pull request? 
We really would appreciate a new release with Jakarta EE support.

**Comment by Kirkunit** [comment]
This would be much appreciated for us as well. Hope it can be prioritized.

**Comment by cess11** [comment]
I'm also in an organisation where this upgrade would be much appreciated.

**Comment by rstoyanchev** [comment]
This is superseded by #1794.
