### ISSUE TITLE
Is Spring Webflow worth using?  Seems dead...

### ISSUE THREAD

**Issue by cbmeeks** [spring-projects/spring-webflow#1803]
I have a project that has some simple workflow elements.  I'd like to use something like webflow but it seems this project isn't very active.  Are there alternatives?

Thanks.

**Comment by rstoyanchev** [comment]
The project is not actively worked on or modernized, but it is not dead. It was upgraded not long ago to a Java 17 and Spring Framework 6+ baseline. I think a lot of applications still find it useful. Whether it helps you is up to you.

**Comment by lucaluse** [comment]
I'm also considering using spring webflow but I can see that open source support ends soon (2024-07-12). Does this mean that I would need to rely on commercial support, which ends after November 2025, or are there any plans for future releases?
https://spring.io/projects/spring-webflow#support

**Comment by krzycho26** [comment]
I am also very interested in knowing what the strategy for Spring Web Flow is.

**Comment by andrei-tytsik** [comment]
+1 is the project still supported?

**Comment by rkalapuc** [comment]
project is really nice, but seems to be outdated and not actively maintained. Could someone from maintainers give us more information about its future?
