### ISSUE TITLE
Let MvcViewFactoryCreator autodetect already registered viewResolvers [SWF-652]

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-webflow#228]
**[Marten Deinum](https://jira.spring.io/secure/ViewProfile.jspa?name=mdeinum)** opened **[SWF-652](https://jira.spring.io/browse/SWF-652?redirect=false)** and commented

Currently if we have multiple view resolvers we need to explicitly define them on the MvcViewFactoryCreator. It would be great if the MvcViewFactoryCreator could detect those itself. Could be configurable (detectViewResolvers and default to 'true'). When detecting it should honor the order property (Ordered interface). It would be a great extension which would mimic the DispatcherServlet behavior.

---

**Affects:** 2.0.0.RC1

**Comment by rstoyanchev** [comment]
This is a valid request. It would have to be configurable, and not on by default since it is not at all clear that all view types apply to WebFlow rendering as well. That said I'm closing for now due to lack of demand.
