### ISSUE TITLE
Documentation contains dead links to samples

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-webflow#906]
**[Lars Grefer](https://jira.spring.io/secure/ViewProfile.jspa?name=larsgrefer)** opened **[SWF-1731](https://jira.spring.io/browse/SWF-1731?redirect=false)** and commented

The reference documentation contains links to https://src.springframework.org/svn/ which are not reachable.

The links can be found in these sections:

https://docs.spring.io/spring-webflow/docs/2.5.0.RELEASE/reference/htmlsingle/#whatsnew-samples

https://docs.spring.io/spring-webflow/docs/2.5.0.RELEASE/reference/htmlsingle/#d5e187

https://docs.spring.io/spring-webflow/docs/2.5.0.RELEASE/reference/htmlsingle/#spring-mvc-embedded-flow-examples

https://docs.spring.io/spring-webflow/docs/2.5.0.RELEASE/reference/htmlsingle/#spring-faces-embedded-mode

 

---

**Affects:** 2.5.0

**Comment by snicoll** [comment]
Most of those were removed in 3.0.x but one was remaining with no alternatives that we could find.
